### ISSUE TITLE
typo: should be "player2.position"

### ISSUE THREAD

**Issue by apang1992** [PacktPublishing/Lua-Quick-Start-Guide#5]
https://github.com/PacktPublishing/Lua-Quick-Start-Guide/blob/01f779a6bbdc20bc9e3d01b368ac24352038f51c/Chapter03/24_tableinobjects.lua#L39

**Comment by SweetyPagaria** [comment]
Hi [apang1992](https://github.com/apang1992), thanks. It's updated.

**Comment by SweetyPagaria** [comment]
Hi [apang1992](https://github.com/apang1992), it is updated. Thanks!
![2023-02-28_12h19_13](https://user-images.githubusercontent.com/106649006/221776519-21a9b082-cc0a-4f9e-859b-d28ddbebdcdd.png)
